export const clinicConfig = {
  name: "Aura Dental",
  legalName: "Aura Dental Clinic Ltd",
  description: "Award-winning implant and cosmetic dentistry designed around your comfort, using state-of-the-art digital technology.",
  tagline: "Transform Your Smile With Confidence.",
  established: 2012,
  contact: {
    email: "hello@auradental.co.uk",
    phone: "020 7123 4567",
    address: {
      street: "124 Wimpole Street",
      city: "London",
      postcode: "W1G 8SY",
      country: "United Kingdom",
      googleMapsUrl: "https://maps.google.com/?q=Wimpole+Street+London",
    },
  },
  openingHours: [
    { day: "Monday", hours: "08:30 - 18:00" },
    { day: "Tuesday", hours: "08:30 - 18:00" },
    { day: "Wednesday", hours: "08:30 - 18:00" },
    { day: "Thursday", hours: "08:30 - 19:30" }, // Late night
    { day: "Friday", hours: "08:30 - 17:00" },
    { day: "Saturday", hours: "09:00 - 13:00" },
    { day: "Sunday", hours: "Closed" },
  ],
  socials: {
    instagram: "https://instagram.com/auradental",
    facebook: "https://facebook.com/auradental",
    twitter: "https://twitter.com/auradental",
  },
  seo: {
    defaultTitle: "Aura Dental | Premium Implant & Cosmetic Dentistry in London",
    defaultDescription: "Transform your smile with confidence. Award-winning implant and cosmetic dentistry designed around your comfort in Central London.",
    keywords: ["Private Dentist London", "Cosmetic Dentist London", "Dental Implants London", "Veneers London", "Invisalign", "Teeth Whitening"],
  },
  treatments: [
    {
      id: "implants",
      title: "Dental Implants",
      shortDescription: "Permanent, natural-looking tooth replacements that restore your smile's function and aesthetics.",
      price: "From £2,500",
      image: "https://images.unsplash.com/photo-1606811841689-23dfddce3e95?q=80&w=2574&auto=format&fit=crop",
    },
    {
      id: "veneers",
      title: "Porcelain Veneers",
      shortDescription: "Custom-crafted ultra-thin shells to instantly correct chips, gaps, and discoloration.",
      price: "From £850 per tooth",
      image: "https://images.unsplash.com/photo-1598256989800-fea5ce5146c1?q=80&w=2670&auto=format&fit=crop",
    },
    {
      id: "invisalign",
      title: "Invisalign",
      shortDescription: "Clear, removable aligners that discreetly straighten your teeth without traditional braces.",
      price: "From £3,500",
      image: "https://images.unsplash.com/photo-1574542616554-47137f6f5773?q=80&w=2574&auto=format&fit=crop",
    },
    {
      id: "whitening",
      title: "Professional Whitening",
      shortDescription: "Safe, effective treatments tailored to brighten your smile by several shades in just one visit.",
      price: "From £395",
      image: "https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?q=80&w=2670&auto=format&fit=crop",
    },
    {
      id: "checkup",
      title: "Comprehensive Checkup",
      shortDescription: "A thorough examination of your oral health, including digital x-rays and cancer screening.",
      price: "£120",
      image: "https://images.unsplash.com/photo-1609840114035-3c981b782dfe?q=80&w=2574&auto=format&fit=crop",
    },
    {
      id: "hygiene",
      title: "Dental Hygiene",
      shortDescription: "Professional cleaning to remove plaque and tartar, preventing gum disease and decay.",
      price: "£95",
      image: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?q=80&w=2670&auto=format&fit=crop",
    },
  ],
  testimonials: [
    {
      id: 1,
      name: "Sarah Jenkins",
      role: "Implant Patient",
      text: "The team at Aura made me feel completely at ease. My new implants look indistinguishable from my natural teeth. Truly life-changing.",
      rating: 5,
    },
    {
      id: 2,
      name: "Michael Chen",
      role: "Veneers Patient",
      text: "I hid my smile for years. After getting veneers here, I can't stop smiling. The attention to detail and luxury service is unmatched.",
      rating: 5,
    },
    {
      id: 3,
      name: "Emma Thompson",
      role: "Invisalign Patient",
      text: "A 5-star experience from start to finish. They explained every step of my Invisalign journey and the results are perfect.",
      rating: 5,
    },
  ],
};
